export const SAVE_AUTH_STATE = "SAVE_AUTH_STATE";
export const CLEAN_AUTH_STATE = "CLEAN_AUTH_STATE";

export const FETCHING_USER = "FETCHING_USER";
export const FETCHED_USER_SUCCESS = "FETCHED_USER_SUCCESS";
export const FETCHED_USER_FAILURE = "FETCHED_USER_FAILURE";

export const FETCHING_BOOKS = "FETCHING_BOOKS";
export const FETCHED_BOOKS_SUCCESS = "FETCHED_BOOKS_SUCCESS";
export const FETCHED_BOOKS_FAILURE = "FETCHED_BOOKS_FAILURE";

export const DELETING_BOOK = "DELETING_BOOK";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const EDITING_BOOK = "EDITING_BOOK";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";

export const ADDING_BOOK = "ADDING_BOOK";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";
